version: '2'
services:
    app:
        image: node-project:latest
        restart: always
        volumes: 
            - './:/app'
        ports: 
            - 80:80
        depends_on:
            - mongo

    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - './data/:/data'